name: my-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - notebook
  - ipykernel
  - pip
  - pip:
      - comet_ml
      - tsaug